### ISSUE TITLE
redirect to custom page on the last slide

### ISSUE THREAD

**Issue by ghost** [lukeed/bee3d#10]
i want to redirect to a custom page on the last slide by using the custom events found here : https://github.com/lukeed/bee3d/wiki/Events

I cant figure out how to implement the script, can you please help me out ?

Envato username : prakashbholah

Best regards

**Comment by lukeed** [comment]
Hi prakashbholah, thanks for leaving your question here!

This is what you need to do:
1. cache the number of slides you have at the beginning of your script
2. on `activate` callback (every slide change), check the current active slides' index.
3. If on the last slide (# of slides minus 1), trigger your redirect

``` javascript
var slider = new Bee3D(elem, {opts});

// (1)
var maxSlides = slider.el.slides.length; 

// (2)
slider.el.on('activate', function(event) {
  if (event.index == maxSlides - 1) {
    // (3), we're on the last slide. go to new URL...
    window.location.href = 'http://google.com';
  }
});

```

**Comment by ghost** [comment]
hello lukeed, i've tried this script and it does not work, maybe I am badly implementing the script.

Here's the full script used :

``` html
<script>
        var element = document.querySelector('.slider_weeklies');

        var slider = new Bee3D(element, {
            effect: 'arc',
            autoplay: {
                enabled: true
            },
            listeners: {
                keys: true,
                touches: true
            },
            navigation: {
                enabled: true,
            },

            /*
            onInit: function(){
                alert('Custom onInit callback function!')
            },
            */

        }); 

        var slider = new Bee3D(elem, {opts});

        // (1)
        var maxSlides = slider.el.slides.length; 

        // (2)
        slider.el.on('activate', function(event) {
          if (event.index == maxSlides - 1) {
            // (3), we're on the last slide. go to new URL...
            window.location.href = 'http://google.com';
          }
        });

    </script>
```

**Comment by lukeed** [comment]
Delete this: `var slider = new Bee3D(elem, {opts});`

I just had that in there as an example.

**Comment by ghost** [comment]
cool man, now it works

thanks a lot :+1:

**Comment by lukeed** [comment]
No problem!
