### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by pmatsinopoulos** [lukeed/bee3d#11]
Hi,

I am trying to run the example code as given in the Getting started section and I am getting the error:

```
RangeError: Maximum call stack size exceeded.
```

I am attaching a picture of the developer tools that shows the error.

![maximum-call-stack-size-exceeded](https://cloud.githubusercontent.com/assets/898286/9608669/315025d0-50d8-11e5-8754-7ee662422365.png)

Can you please help? Here is the code of my HTML page that is doing the integration with bee3D.

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
    <title>untitled</title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="generator" content="Geany 1.23.1" />
    <link href="styles/bee3D.min.css" rel="stylesheet">
</head>

<body>

    <!-- Bee3D Slider Markup -->
  <div id="wrapper">
    <article>
      <section>Slide 1</section>
      <section>Slide 2</section>
      <section>Slide 3</section>
    </article>  
  </div>

<!-- At bottom of page -->
<script src="scripts/dependencies/classie.js"></script>
<script src="scripts/bee3D.js"></script>

<!-- Now we create a new slider -->
<script>
  var slider = new Bee3D('article', {
    wrapper: document.getElementById('wrapper'),
    effect: 'concave',
    // ... more options here
  });
</script>

</body>

</html>
```

**Comment by lukeed** [comment]
Sorry, there was a typo in the Getting Started example :-1: Please [see updated](https://github.com/lukeed/bee3d/wiki/Getting-Started)
I had copied it from Version 1's documentation -- Oops!

Just so you know, `new Bee3D('article')` was causing the issue because `'article'` isn't an element. It was missing a document selector method.
