### ISSUE TITLE
Misalignment between example in Options section and Getting Started

### ISSUE THREAD

**Issue by pmatsinopoulos** [lukeed/bee3d#12]
I see that the example in option section of the documentation: https://github.com/lukeed/bee3d/wiki/Options#example does not initialize the Bee3D the same way like the Getting Started example does.

This really confuses me on how Bee3D should be initialized. 

In particular, the example in options 

```
var el = document.getElementById('demo');
var slider = new Bee3D(el, {
```

initializes `Bee3D` with an HTML element as returned by `document.getElementById()`.

Wheres in Getting Started section it initializes it using the selector of a HTML tag that's inside the wrapper HTML element.

**Comment by lukeed** [comment]
Both examples are using different ways to target a single element. That's just normal Javascript.

If you had this example: `<div id="demo" class="demo--class"></div>`

You could target it like this:

``` javascript
document.getElementById('demo')
document.querySelector('.demo--class')
document.querySelector('div') // assuming this is the only 'div' on the page
```

You probably are more familiar with jQuery. So in jQuery, you would normally do:

``` javascript
$('#demo')
$('.demo--class')
$('div')
```

jQuery is executing the plain Javascript examples behind the scenes.

Multiple ways to target the same element.
But Bee3D uses plain Javascript (it's faster), so those are examples of how you can initialize Bee3D on an element.
