### ISSUE TITLE
Gap between slides of different sizes

### ISSUE THREAD

**Issue by bluesix** [lukeed/bee3d#15]
Is it possible to have the gap between slides shrink or grow depending on the relative size of the slide? For example, if I change my slide to 250px x 250px, the gap becomes huge as it's set in the CSS for  512px wide slides.
Note: the slides will be all the same size in the deck.

**Comment by lukeed** [comment]
Yes you can. You're looking for the transform values for your desired effect.

You can find them in `src/styles/effects`

For example, `_classic.sass` has the values of -1920px, -1280px, -640px, 1920px, 1280px, 640px.

If you wanted your new slides to be 250px wide with 50px gaps in between each slide, 250 + 50 = 300. So then we increment each slide by this much.

Our new values become these: -900px, -600px, -300px, 900px, 600px, 300px

**Comment by bluesix** [comment]
Yup, I changed those manually myself as there didn't appear to be a way to do it dynamically (e.g. by a JS property).

One thing that I couldn't figure is that the CSS rules have duplicate translateX properties? Never seen that before.
![image](https://cloud.githubusercontent.com/assets/195220/9950134/7f91cf62-5dfa-11e5-82ae-0bbc69c488a0.png)

**Comment by lukeed** [comment]
Yea, unfortunately the JS just sets up the slider, controls the classes on each slide, and listens to events. I did a few tests where JS also calculated & animated the transformations, but that forfeited 60fps.

Re: duplicate X-translations

After rotating, translations are applied to the new axis. I don't really know how to explain it other than by suggesting you open up ChromeDev and play with the 1st & 2nd translations separately on the same slide. The slide will be nudged in different directions, despite both being "X"
