### ISSUE TITLE
minimum loop just working 5 section class

### ISSUE THREAD

**Issue by jeffs1910** [lukeed/bee3d#17]
I have try for example looping, but with 3 section it can't spinning/rotary like clockwise, but with 5 section class.. it's working rotary.

any idea with that to run 3 section class and loop still always continues?
because with your example is like 10 section class and i just need 3 but still spinning.

**Comment by jeffs1910** [comment]
problem is solved... i have modification the CSS and it's working

**Comment by lukeed** [comment]
Cool. Glad you could resolve it @jeffs1910 ! 
Sorry, I was out of the office all day.
