### ISSUE TITLE
how to resize slides?

### ISSUE THREAD

**Issue by shotrox** [lukeed/bee3d#18]
I am looking everywhere to find out how to size the slides... No CSS can be applied. The examples don't work so no help to be found there...
Can you help?

Thanks

**Comment by lukeed** [comment]
You need to check the `src` directory, which is where all the source files are.

Within `src/styles/_config.sass`, there are two SASS variables named `$slide-w` and `$slide-h`. Changing these will change the size of your slides. All of the slider's effects are calculated from these two values.

**Comment by lukeed** [comment]
@shotrox solved?
