### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by nyariv** [lukeed/bee3d#19]
Is there support for lazy loading of images? Or is it at least compatible with other lazy loading libraries like [lazyload](https://github.com/verlok/lazyload)?

**Comment by lukeed** [comment]
There isn't direct support, but it's definitely compatible with other libraries. Just add the necessary markup  (`data-original`) to the slides and then initiate LazyLoad on Bee3d's `onInit` callback.

**Comment by lukeed** [comment]
Did this answer your question? @nyariv

**Comment by nyariv** [comment]
Yes, I believe. Was it tested? Because I know it depends on if the items
are visible within the container or viewport.

**Comment by lukeed** [comment]
Yes, it works. The DOM is there on window load event, so any plugins that rely on declarative market / values will work as if they had been called on a "ready state" event. 

As mentioned, the difference is that you have to initialize the plugin on Bee3d's `onInit` callback.

**Comment by nyariv** [comment]
OK, great. Thanks!

**Comment by lukeed** [comment]
Np :)
