### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by mathishuettl** [lukeed/bee3d#20]
Hello,

i just see a blank page, but why?
http://valete.ep-vorschau.at/

**Comment by lukeed** [comment]
Please finish the rest of the [Getting Started guide](https://github.com/lukeed/bee3d/wiki/Getting-Started#customizing).

You need to add some basic positioning to `#demo` and some background colors to the slides.

If you'd like to see some FULLY working examples, look within the `examples` directory included in your downloaded package.

Marking as closed. Thanks!
