### ISSUE TITLE
I'm sorry, but main function in slider is fake

### ISSUE THREAD

**Issue by medzhidov** [lukeed/bee3d#22]
"onInit" started before, how slider.el begin working. And how i can work with it? 

> "onInit just for fun, friend, take it easy" - okay

I need it for create ol>li navigation, what should be default...
Can u fix it?
May be something i do wrong?

``` JS
var tvslider = new Bee3D( document.querySelector('#main .tv .slider'), {
        onInit: function(something){
            console.log(tvslider); // undefined
            console.log(something); // undefined ?!
        }
    });
```

**Comment by medzhidov** [comment]
Just add

``` JS
this.options.onInit(this);
```

instead of 

``` JS
this.options.onInit();
```

and everybody will be pleased

**Comment by lukeed** [comment]
No, it's not fake. Your code just needs fixing.

Btw, you also have access to the Bee3D source files, so you _could_ alter the `onInit` call yourself. I choose not to because there is no need. 

``` js
var elem = document.querySelector('#main .tv .slider');

// 'slider' refers to the Bee3D object itself.
var slider = new Bee3D(elem, {
  onInit: function () {
    console.log(elem); // div.slider ...
    elem.innerHTML += ....
  }
})
```

**Comment by medzhidov** [comment]
U don't understand me.
I want to know count of slides inside 'onInit' func.
I can get element, but I can't get bee3d object inside 'oninit' function of this element.
Try use 'slider' variable and u get error.
For fix it I suggest add bee3d object inside callback parameters

**Comment by lukeed** [comment]
You have three options:

1) Like I said, edit Bee3D.js yourself & pass in the object

2) Run a query on the `elem` node, assuming you're not dynamically adding slides.

``` js
var elem = document.querySelector('#main .tv .slider');

// 'slider' refers to the Bee3D object itself.
var slider = new Bee3D(elem, {
  onInit: function () {
    var count = elem.getElementsByClassName('bee3D-slide').length;
  }
})
```

3) Run a `setTimeout` inside of `onInit` to pick up the `slider` variable. (You can _never_ read a variable from within **while** you are still declaring its first value.)

``` js
var slider = new Bee3D(elem, {
  onInit: function () {
    setTimeout(function () {
      console.log(slider); // Bee3D {}
      console.log(slider.el.slides.length); // Integer
    }, 0); // will happen instantly
  }
})
```

**Comment by medzhidov** [comment]
I just suggest add it in your sources, for make it more useful.
Main direction in your product is "source development", because i got many files for create source of this slider (gulp, sass and more), but if i bought slider, i think it has some standarts functions and for create simple slider i'll not change source.
Thx for support. Good slider.

**Comment by lukeed** [comment]
Thanks, please rate :+1:
