### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by cuunonhaitac** [lukeed/bee3d#23]
Hi, I have bought bee3d plugin and I have problem with the file css,js (that relate bee3d) can't be access with a status of 403 when I upload on local host. How can i solve this issue?

**Comment by lukeed** [comment]
Hey there,

403 is a `Forbidden` status code. That's something to do with your server setup, and not with Bee3D.

**Comment by cuunonhaitac** [comment]
Other file css, js is still work except files relate Bee3D. So I think the reason is not my server setup.

**Comment by lukeed** [comment]
Do you have a link?

I'd make sure the `chown` users match the rest of the files.

**Comment by lukeed** [comment]
Inactive.
