### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by cuunonhaitac** [lukeed/bee3d#25]
Hi lukeed,

I have some problem with the source code bee3d.
This is my link of my website: 
http://shop.saigonboardgame.com/
You can click on menu on top-left to show navigation. After that, you click some category that below homepage link, this is where I use bee3d plugin.
But there are a issue, It is not working and I see the error: "Uncaught SyntaxError: Unexpected token <" in file bee3d.min.js. I have run this one in localhost and it ok, but when I upload on server, it doesn't run. Can you check for me and how to solve this problem?

Regards,

**Comment by lukeed** [comment]
Hi there,

It seems to be working for me. Did you manage to solve your own issue?
I'm on Chrome

**Comment by lukeed** [comment]
Closing: not reproducible + inactive.
