### ISSUE TITLE
Begin with second slide

### ISSUE THREAD

**Issue by clivio4** [lukeed/bee3d#26]
Is it possible to begin with the second slide? So that 3 slides are visible from the start? One on the left, one in the center and one in the right? Now when slideshow starts, I see only center and right slide, left is blank and it doesn't look good. Thank you in advance.

**Comment by lukeed** [comment]
Yes, use the `focus` option. It's 0-based so the **first** slide is `0`, and the **second** is `1`.

``` js
new Bee3D(element, {
  focus: 1
});
```

**Comment by lukeed** [comment]
[Options Reference](https://github.com/lukeed/bee3d/wiki/Options#basic-options)

**Comment by clivio4** [comment]
Thank you very much!

**Comment by lukeed** [comment]
No problem :)
