### ISSUE TITLE
SCRIPT5009: 'Symbol' is undefined IE 11

### ISSUE THREAD

**Issue by darshanmarathe** [lukeed/bee3d#27]
Hi 

It rhows 'Symbol' is undefined and stops working

Looks like it need ES6 shim or compile through right compiler 

We shortlisted this but rejected this cause IE 10 , 11 Support 

Let me know if you can fix this by 28 April 2016 so i can foword this 

Regards
Darshan
darshanmarathe@gmail.com

**Comment by lukeed** [comment]
Ah, yea. Looks like an easy transpiling issue. I'll fix that.

**Comment by lukeed** [comment]
@darshanmarathe I spent the day fixing this. Symbols have been removed entirely, so it will work in IE10 and older Safaris once again.

However, I did not update the demo pages. My demo setup uses Babel heavily and I don't want to rewrite it all at this time. (Babel is what injects the `Symbol` instances).

Thanks for reporting the issue.

**Comment by darshanmarathe** [comment]
Awesome this is awesomely good
