### ISSUE TITLE
Unable to follow Developers Quick start Steps

### ISSUE THREAD

**Issue by rahuljadav** [lukeed/bee3d#30]
``` bash
cd path/to/bee3D
npm install
npm run fly
```

getiing the below mentioned error

after following the above steps
stack:
- Error: Did you forget to `npm i -D fly-autoprefixer`?
-     at D:\wamp\www\bee3d\node_modules\fly\lib\fly.js 66:10
-     at Array.forEach (native)
-     at new Fly (D:\wamp\www\bee3d\node_modules\fly\lib\fly.js 64:10)
-     at Object.module.exports [as spawn](D:wampwwwbee3dnode_modulesflylibclispawn.js 20:9)
-     at next (native)
-     at onFulfilled (D:\wamp\www\bee3d\node_modules\fly\node_modules\co\index.js 65:19)
  message: Did you forget to `npm i -D fly-autoprefixer`?

**Comment by lukeed** [comment]
Ah, thanks for the reminder! Some packages are out of date. I'll publish an update later today as it's the end of the day for me right now.

**Comment by lukeed** [comment]
Closed, update just submitted to CodeCanyon!
