### ISSUE TITLE
npm i -D fly-autoprefixer Error

### ISSUE THREAD

**Issue by fiona-manzella** [lukeed/bee3d#36]
Hey! Downloaded your library from Code Canyon, and saw this issue was "closed" a few months ago: https://github.com/lukeed/bee3d/issues/30

But I am still seeing the same error. When I run `npm install` i get a couple of deprecation errors
```npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

``````
but it seems to run ok. `npm run fly` just returns 
```stack: 
  - Error: Did you forget to `npm i -D fly-autoprefixer`?
  -     at ~/website_repo/wp-content/themes/prismtheme/js/bee3d-slider-js/node_modules/fly/lib/fly.js 91:10
  -     at Array.forEach (native)
  -     at new Fly (~/website_repo/wp-content/themes/prismtheme/js/bee3d-slider-js/node_modules/fly/lib/fly.js 89:10)
  -     at Object.module.exports [as spawn] (~/website_repo/wp-content/themes/prismtheme/js/bee3d-slider-js/node_modules/fly/lib/cli/spawn.js 24:9)
  -     at next (native)
  -     at onFulfilled (~/website_repo/wp-content/themes/prismtheme/js/bee3d-slider-js/node_modules/fly/node_modules/co/index.js 65:19)
message: Did you forget to `npm i -D fly-autoprefixer`?
``````

Is there a fix I can run for this?

**Comment by lukeed** [comment]
hey there, I just submitted an update because someone else emailed me with a similar issue.

In your `package.json`, change the `fly` dependency from `^1.3.0` to `1.3.0` (no "^"). Then re-install all modules with `npm`.

```
rm -rf node_modules
npm install
```

**Comment by fiona-manzella** [comment]
Hey! Thanks for the fast response. I gave that a shot but am still seeing the same error message. Tried a second time after removing the carrot prefix from all `devDependencies` but no dice. Thoughts?

**Comment by lukeed** [comment]
Hmm... please paste your full stack trace? And I'll be able to tell what OS you're on with that, but what about Node version?

**Comment by fiona-manzella** [comment]
Updating node and npm worked like a charm! Thanks!

**Comment by lukeed** [comment]
Cool, cheers!
