### ISSUE TITLE
styles failed due to Error: File to import not found or unreadable: components/* e sheet: E:/bee3d-slider/bee3D.sass

### ISSUE THREAD

**Issue by oh-cheezburgers** [lukeed/bee3d#37]
I'm having trouble getting Bee3D to work, after installing when running 'npm run fly' I get the error message 'Error: File to import not found or unreadable: components/* Parent style sheet E:/bee3d-slider/bee3D.sass'

When running in a browser the slider does not render, only showing numbers.

![screenshot 2016-11-03 11 04 37](https://cloud.githubusercontent.com/assets/3510774/19963680/5f0ca3fc-a1b5-11e6-9a0a-d636c45ce227.png)

Chrome's console shows all CSS files and the bee3D.js file as missing.

![screenshot 2016-11-03 11 06 03](https://cloud.githubusercontent.com/assets/3510774/19963720/94f55b6c-a1b5-11e6-865a-92a04278b72f.png)

Running Node.js v6.9.1 with NPM v3.1.0.

Output from the cmd window can be found below: 
[error.txt](https://github.com/lukeed/bee3d/files/568779/error.txt)

**Comment by lukeed** [comment]
Ah, shoot. I need to post an update to Envato with a shrink wrap of the build tools.

The packages are resolving to versions that aren't fully compatible anymore. I'll send you the shrink wrap first, circa 20m.

Thanks!

**Comment by lukeed** [comment]
Place this file in your project's root (next to the `package.json` file) then **rename** it to `npm-shrinkwrap.json`.

It's currently `.txt` so that I could upload it to GitHub: [npm-shrinkwrap.txt](https://github.com/lukeed/bee3d/files/569535/npm-shrinkwrap.txt)

**Comment by oh-cheezburgers** [comment]
Thanks for the reply. Better but still getting problems with being unable to import the components folder.

New error log attached: [error.txt](https://github.com/lukeed/bee3d/files/571239/error.txt)

**Comment by lukeed** [comment]
@oh-cheezburgers Hm.... you have that file correct?

Try renaming `components/_*.sass` to `components/_all.sass` (or whatever) and then update the `@import` path. You may have to do this for each `@import` that contains a `*`

I have no idea why this would be happening, and I can't replicate it. Are you on Windows by chance?

**Comment by oh-cheezburgers** [comment]
I've tried installing it within a Linux-based disto, new errors.

Would you be able to supply compiled js/css files?

[npm-debug.txt](https://github.com/lukeed/bee3d/files/583124/npm-debug.txt)

**Comment by lukeed** [comment]
Sure, please email me: luke at lukeed.com

**Comment by lukeed** [comment]
Never got an email from you 😢 

Happy to help, but need more info. There's also been updated versions since this issue was opened. They should have solved this issue.
