### ISSUE TITLE
Slide Size

### ISSUE THREAD

**Issue by rosentoski** [lukeed/bee3d#44]
I need to change the slide size and I'm wondering the best practice for doing so. I have read the other issues and it seems there are a few ways to get this done.  If I change the variables in the scss files i have to rebuild the project before I use the dist js and css files in my project, or am I supposed to include the sass files on my website before I build it out? Or do you recommend just adding custom css to my scss files to override existing?

**Comment by lukeed** [comment]
Hi there! Sorry for the delay -- was away from my desk most of the day.

I would definitely do it with the SCSS files & then recompile. Are you trying to avoid that step? If so, how come?

And yes, you would need to rebuild before attaching the updated styles (as a `.css` file) to your website.

The variables you're looking for are found in `bee3d-slider/src/styles/_config.sass`. Changing `$slide-w` and `$slide-h` will recalculate & adjust all effects' values for you.

**Comment by rosentoski** [comment]
I have done changed the $slide-w and $slide-h and the slide does change size, however, it leaves all the space between the slides. The transform: translateX is not changing with the set variables.
Nice job on this carousel and thank you for the quick response.

**Comment by lukeed** [comment]
Oh, shoot. Somewhere along the line, the math calculations for transformations' values disappeared.

I'll add those back in & cut a new release. Will reply here once that's been queued for publishing.

**Comment by lukeed** [comment]
Closing this in favor of the linked issue. I'll still comment here once the change has been made! 😄
