### ISSUE TITLE
Use SASS vars to calculate effects' values

### ISSUE THREAD

**Issue by lukeed** [lukeed/bee3d#45]
This way, any changes to `$slide-w` or `$slide-h` will automatically adjust the transformations for all effects.

This used to be included circa v1.0, but got lost somewhere along the way. 🤔 

---

Piggybacks #44

**Comment by leolux** [comment]
What is the status of the transformation caculations? Today I bought the product on envato which is labeled with version 2.0.0. How to change the slide size there?

**Comment by lukeed** [comment]
Hi there, thanks for your purchase!

Where are you seeing "2.0.0"? I just downloaded the package from CodeCanyon and it's on version `2.3.1` --- look at the "version" key inside `package.json`

To change the slide sizes, I recommend you look at #44, #50 and #32. 

I'm closing this issue because I forgot to earlier -- percentage-based changes for effects landed in v2.3.0

**Comment by leolux** [comment]
Thanks! I got the version info from the following picture https://s3.envato.com/files/145067106/Envato-590x300.jpg

**Comment by lukeed** [comment]
Oh haha, oops! I should probably remove that. Updating those things via Envato is a real PITA
