### ISSUE TITLE
Show More Slides

### ISSUE THREAD

**Issue by arevenon** [lukeed/bee3d#46]
Is it possible to display more slides with current options? Instead of showing only 5 slides / partial slides I would like to display potentially 11-15.

**Comment by lukeed** [comment]
Yes! You can show as many as you like. The [demos](https://www.lukeed.com/demo/bee3D/#/basic) have 10 slides, for example.

You just have to provide the markup. Here's an [AJAX example](https://www.lukeed.com/demo/bee3D/#/ajax/basic) that starts with 10, then adds 5 more (11-15).

Let me know if you have any more questions :)
