### ISSUE TITLE
How to enable autoplay manually?

### ISSUE THREAD

**Issue by mrdubz** [lukeed/bee3d#48]
Hi!
I have slider with 'autoplay: false', but i need start autoplay manually by event in other script. 
Is it possible?

Thanx!

**Comment by lukeed** [comment]
Hello, Yes! Simply call the `autoplay()` function on your slider.

```js
var element = document.querySelector('.example');

var slider = new Bee3D(element, {
  effect: 'carousel',
  listeners: {
    keys: true
  },
  navigation: {
    enabled: true
  }
});

// later...

slider.autoplay();
```

You can set the [`autoplay.speed`](https://github.com/lukeed/bee3d/wiki/Options#autoplay) value ahead of time & it will be used whenever you decide to begin `autoplay`ing.

Let me know if that helps 😃
