### ISSUE TITLE
change slider effect on the fly

### ISSUE THREAD

**Issue by bUxEE** [lukeed/bee3d#51]
Hello again! 
(sorry for spam on help issues)
Ho can I change the slider effect on the fly? I tried:
`sliderName.effect('classic')`
`sliderName.effect = 'classic';`
`sliderName.config.effect = 'classic';`
but it is not working.

update*
I noticed that with nav arrows and drag the infinite loop does not work.

**Comment by lukeed** [comment]
Hi @bux23, no problem! I'd much rather you ask questions than be stuck/unhappy with the product.

You have to reinitialize the slider with the new effect name. You should save the options into an object, then initialize Bee3D with the new effect name. This is exactly how I do it in my demos.

```js
var elem = document.getElementById('slider');
var config = {
  effect: 'carousel',
  // ... all your initial options
};

// first init
var slider = new Bee3D(elem, config);

// change effect
config.effect = 'coverflow';

// grab the currently-active slide
// so that you don't restart from beginning
config.focus = slider.el.slide();

// re-init
slider = new Bee3D(elem, config);
```

It may _seem_ counterintuitive, but the initializer is so quick that there's no penalty. All classnames will be updated and you'll see them transition into place 😄

**Comment by bUxEE** [comment]
ah ok! good to see that I can simply reinitiate the same slider over directly. I was using destroy, and 
 initiating it again in onDestroy callback.
Will apply it tomorrow... Thanks!!!!! :smile:

**Comment by lukeed** [comment]
Haha, you _can_ do that, but it's a little more expensive of a call. TBH, I used to do that in the demos, but found that this approach was much faster & smoother.

**Comment by bUxEE** [comment]
M8, I have tried doing as you explained and weirdly it gives correct parameters when logging the slider object before and after the change  but the slider does not visually change. (stays cube)

console log:
```
BEFORE
r {options: Object, el: Object}
el:Object
options:Object
ajax:Object
autoplay:Object
effect:"cube"
focus:1
listeners:Object
loop:Object
navigation:Object
onChange:function e()
onDestroy:function e()
onInit:function ()
parallax:Object
selector:".bee3D--slide"
shadows:Object
sync:Object
wrapper:body.page-template-default.page.page-id-404.fullwidth.hide-title-bar-no.theme-skin-light.footer-default.header-is-sticky.header-mobile-is-sticky.no-mobile-slidingbar.rev-position-header-below.one-col.wpb-js-composer.js-comp-ver-5.1.1.vc_responsive.pace-done
__proto__:Object
__proto__:Object

AFTER
r {options: Object, el: Object}
el:Object
options:Object
ajax:Object
autoplay:Object
effect:"classic"
focus:1
listeners:Object
loop:Object
navigation:Object
onChange:function e()
onDestroy:function e()
onInit:function ()
parallax:Object
selector:".bee3D--slide"
shadows:Object
sync:Object
wrapper:body.page-template-default.page.page-id-404.fullwidth.hide-title-bar-no.theme-skin-light.footer-default.header-is-sticky.header-mobile-is-sticky.no-mobile-slidingbar.rev-position-header-below.one-col.wpb-js-composer.js-comp-ver-5.1.1.vc_responsive.pace-done
__proto__:Object
__proto__:Object
```

**Comment by lukeed** [comment]
Hmm... can you paste how you are calling it?

I know it works -- it's almost the exact code that powers the demos.

**Comment by bUxEE** [comment]
```
var curW =  $(window).width();
$(window).on('resize', function() {
            var WW = $(window).width();

            resize_bee_slider(id, size);
            
            if( (curW >= 768 && WW < 768) ) {

                args.focus = window[sliderName].el.slide();
                args.effect = "classic";
                console.log(args)
                console.log('before')
                console.log(window[sliderName]);
                window[sliderName] = new Bee3D(el, args);
                console.log('after');
                console.log(window[sliderName])

            } else if (curW < 768 && WW >= 768) {

                args.focus = window[sliderName].el.slide();
                args.effect = beeType;
                console.log(args)
                console.log('before')
                console.log(window[sliderName]);
                window[sliderName] = new Bee3D(el, args);
                console.log('after')
                console.log(window[sliderName]);

            }
            curW = WW;
        });
```

not giving any errors in log

**Comment by lukeed** [comment]
Are you sure the `el` from `new Bee3D(el, args)` is a dom node & **not** a jQuery-selected node?

**Comment by lukeed** [comment]
Oh, I know. Your `if` and `else if` are wrong.

Your `curW` is only set once -- _before_ resize. So that means that `curW` will always be, for example, 680px. Even if you resize it to 1024px, the second condition is still true because: 

```js
(680 < 768 && 1024 >= 768)
//=> true
```

**Comment by bUxEE** [comment]
its also set at end of function :) those work properly I can tell by looking at console log.  infact as pasted everytime I cross the breakpoints the object properties change properly, but the slider visually doesnt -.-

you want me to set up a demo slider?

**Comment by lukeed** [comment]
> you want me to set up a demo slider?

Please. Just a basic HTML file. Then you can ZIP it up & email it to me 👍

**Comment by bUxEE** [comment]
I don't seem to find your email address anywhere

**Comment by lukeed** [comment]
Hi! Sorry, you can send me a message here: https://themeforest.net/user/lukeed

Then I will reply via my email. I don't want to post my email because I've been spammed a few times before 😞

**Comment by lukeed** [comment]
Resolved in email 👌
