### ISSUE TITLE
Slide covers navigation elements when using an unpropotional scale factor

### ISSUE THREAD

**Issue by leolux** [lukeed/bee3d#52]
One way to make the slides repsonsive is to scale them up/down based on the dimension of the container width. Another idea would be to change the number of visible slides based on the device size (for example by using CSS media queries.). This way the slides displayed on small devices could be rendered bigger compared to the scaled slides.

On the other hand choosing a scaled factor which is unpropotional to the container size can also result in reasonable big slides. I noticed an issue here because the navigation elements are no longer visible and clickable if the slide covers the full width of the screen. When setting the "z-index" of "bee3D--nav__next/prev" to "1" the issue gets fixed.

Did you face the same problem?

**Comment by lukeed** [comment]
I think responsiveness is totally a user-dependent // subjective opinion. I've made it possible to easily do whatever your app requires. Had I shipped a default "This is how it's going to work", then I'd have a lot more people complaining IMO.

Have you checked out #4 and #28? I suggest applying scale-transformations to your `bee3D--parent` element, tied to media queries. If all your elements are within that node, then they are all equally scaled down. You can then (cheaply) scale up child-nodes that have become too small.

Doing this, I've never run into a scenario wherein I could not control the layout, including navigation items!

Let me know if you have additional question.

**Comment by leolux** [comment]
I totally agree. After checking out #28 I thought that the options described there are "either-or" alternatives. But applying transformations to both parent and children allows for an even better control. So the issue with covered navigation items does not even appear.

Since most scenarios can be managed this way I can close this issue. Thanks to lukeed!
