### ISSUE TITLE
Sync giving "Uncaught TypeError" message

### ISSUE THREAD

**Issue by heronymo** [lukeed/bee3d#54]
Hi there.

I'm having an issue syncing 2 sliders. I have one slider broadcasting to the other slider, but not the other way around.

Here's the error:
```
Uncaught TypeError: Cannot read property 'el' of undefined
    at t (bee3D.js:1)
    at bee3D.js:1
    at Array.reduce (<anonymous>)
    at s (bee3D.js:1)
    at r (bee3D.js:1)
    at l (bee3D.js:1)
    at Object.c [as slide] (bee3D.js:1)
    at HTMLDivElement.o (bee3D.js:1)
```

And here's the JS, which appears below the HTML.

```
jQuery(document).ready(function(){
			var getfeaturetextslider = document.getElementById('featureslider-text');
			var featuretextslider = new Bee3D(getfeaturetextslider, {
			  effect: 'classic',
			  focus: 1
			});
			
			var getfeatureimageslider = document.getElementById('featureslider-images');
			var featureimageslider = new Bee3D(getfeatureimageslider, {
			  effect: 'coverflow',
			  focus: 1,
			  listeners: {
				  keys: true,
				  clicks: true
			  },
			  sync: {
				  enabled: true,
				  targets: ['featuretextslider']
			  }
			});
		})
```

Any ideas why this might be happening? To test both sliders, I added listeners to each and removed the sync and they both work just fine without it.

**Comment by lukeed** [comment]
Hey there!

Try mounting the sliders to the `window` global, so that they are definitely available. For example:

```js
window.featuretextslider = new Bee3D( new Bee3D(getfeaturetextslider, {
  effect: 'classic',
  focus: 1
});

window.featureimageslider = new Bee3D(getfeatureimageslider, {
  effect: 'coverflow',
  focus: 1,
  listeners: {
    keys: true,
    clicks: true
  },
  sync: {
    enabled: true,
    targets: ['featuretextslider']
  }
});
```

This test will see if the slider names are being mangled // hidden from each other in anyway.

> Admittedly, the system for `sync`ing sliders isn't the best. I want to improve this in future versions!

If you _intend_ to only broadcast one slider to the other, I would suggest using the [`onChange`](https://github.com/lukeed/bee3d/wiki/Options#callbacks) option (or [`slider.el.on('activate')`](https://github.com/lukeed/bee3d/wiki/Events#event-listeners) event) of the control-slider to update the other.

```js
var text = new Bee3D(..., { ... });
var images = new Bee3D(..., { ... });

images.el.on('activate', function (event) {
  var index = event.index; // the active slide's index
  text.el.slide(index); // update the other slider!
});
```

This is what `sync` does behind the scenes.

**Comment by heronymo** [comment]
Mounting the sliders to "window" worked! Thanks! And also I really appreciate the quick response.

I've left in the normal sync commands, but do you strongly suggest I should change it?

**Comment by lukeed** [comment]
Cool!

Yeah, if that's all you're doing, I (personally) would prefer using the snippet I provided. Using `sync` is geared more towards having _many_ broadcasters _and_ listeners, or having sliders that are broadcasting & listening.

Put differently, `sync` does a lot more than you actually need in this case.

If you don't like the syntax, you can try this instead:

```js
var images = new Bee3D(... {
  onChange(event) {
    text.el.slide(event.index); // same thing
  }
});
```

**Comment by heronymo** [comment]
Cool, makes sense! I do like efficiency. I've switched it to your "on" commands. Works perfectly.

Thanks again for your help!

**Comment by heronymo** [comment]
While I'm here, I actually have an unrelated question.

I was just trying to do this myself, but maybe there's already a solution (or I missed something in the doc).

I'd like the slider to affect the height of the parent div that it's sitting in. Essentially I'm trying to find an efficient way to make it responsive. :)

I tried a couple of quick things but it kind of broke the positioning.

**Comment by lukeed** [comment]
Haha, no problem.

"Affect the height" how? 

Generally it's best to set the parent height first (via CSS) and have the slides fill in the space. It's easier to control mobile/responsive sizing this way too. 

But, that's not the only way. You can access the DOM element from within `onInit` and affect the parent, but am hesitant to recommend that for reasons above.

**Comment by heronymo** [comment]
So for example, let's say I've got a div with no set height (I suppose it's technically set to 'auto') but it has a padding of, say, 200px on the top and bottom. The slider sits inside of this div.

So without the slider (or any other content) within that div, the div would have a height of 400px. But I want the slider to make that div grow. That way, when one is resizing the window, or is on various mobile devices, the entire div + slider fits nicely in the viewport. Or rather, the space above and below the slider is always the same (200px each, for example).

By "parent" do you mean the bee3D--parent?

**Comment by lukeed** [comment]
Does [this](https://jsfiddle.net/lukeed/budth6a4/) work for you? 

The CSS on your `div` has the padding, and then all you have to do is worry about setting the bee3D--parent height, as recommended.

**Comment by lukeed** [comment]
Oh, and worth mentioning that the `blue` background doesn't show up (which is okay), because those slides are absolutely positioned via Bee3D within the parent.

**Comment by heronymo** [comment]
Hmm I put it in, but the slide content isn't affecting the slide size, which in turn doesn't affect the parent size, and then the main div size.

That could just be an issue with my CSS for the slide content. I'll have to play around with it some more next week.

If I can't figure it out I'll be back here lol. Thanks again!
And if I find a solution I'll also post it here in case others can use it.

**Comment by lukeed** [comment]
No problem. Here is a [live example](https://bioscibd.com/effective-royalty-rates) of a production, responsive slider.

You can poke around the styling there, but it uses my recommended approach FYI.

Closing this thread, since the original question was answered haha. Feel free to open a new one if/when you need. 👍
