### ISSUE TITLE
Add Text to Slider / Contao

### ISSUE THREAD

**Issue by yelloweight** [lukeed/bee3d#58]
Hi there. 
Is it possible to add any text to every image in the slider?
e.g in a accordion under the images.
Does someone have any experience in using bee3d in contao?
Thanks for your reply!

**Comment by ghost** [comment]
I was able to add text within my slide using html and css, then on hover or active show the text.

**Comment by lukeed** [comment]
Hi there, yes you can add whatever you want to the slides' contents. That part is up to you entirely!
