### ISSUE TITLE
Downloaded Plugin is not working

### ISSUE THREAD

**Issue by tiffanygct** [lukeed/bee3d#61]
Hi,

The downloaded plugin which I had purchased last week is not working. I had tried to launched "index.html" from src folder and it is not loading.

What are the steps that I have missed?

Regards.

**Comment by lukeed** [comment]
Hey there!

You have to install the local dependencies and build the actual files. The source files are not browser-compatible & instead are in developer language for ease of use.

There's a development guide here: https://github.com/lukeed/bee3d/wiki/Development

**Comment by tiffanygct** [comment]
Hi,

Thank you for the reply.

After i run "npm install", I have the following errors that prevent me to build:

30718 error code ELIFECYCLE
30719 error errno 1
30720 error node-sass@3.13.1 postinstall: `node scripts/build.js`
30720 error Exit status 1
30721 error Failed at the node-sass@3.13.1 postinstall script.
30721 error This is probably not a problem with npm. There is likely additional logging output above.
30722 verbose exit [ 1, true ]

**Comment by lukeed** [comment]
What version of Node are you running? (`node -v`) And where is your Node located? (`which node`)

**Comment by tiffanygct** [comment]
I'm running v8.9.4 and it is located at C drive > Program Files.

**Comment by lukeed** [comment]
Sorry, no experience with Windows but i know `npm` & Windows don't always get along 😖 I'd look thru here for possible solutions: https://github.com/sass/node-sass/issues/1980

Seems like it's like a permissions thing.

**Comment by tiffanygct** [comment]
The requirement in "Development" wiki does not stated that it requires Linux to install relevant components for sliders.

I refer to the link that you shared, none of the solutions work for me.

Any idea how to resolve it?

**Comment by lukeed** [comment]
It doesn't require Linux -- I've built Bee3D (and many other SASS-based projects) on a Windows machine. It's just that it's been so long ago that I can't remember the correct permissions you need.

I can send you the compiled CSS if you'd like, but other than that, the best I can do is link out other Windows + NPM guides.

**Comment by tiffanygct** [comment]
Complied CSS does not require node install?

**Comment by lukeed** [comment]
Nope~! Here's _all_ the built, uncompressed files: [dist.zip](https://github.com/lukeed/bee3d/files/1738793/dist.zip)

**Comment by tiffanygct** [comment]
Thanks, it's working perfectly. 

Sorry, I have one more question. How to move demo text below the box? 

Thank you.

**Comment by lukeed** [comment]
Sorry, I just realized that I sent you the `dist` folder without all the example HTML files included 🙈 

This one has all the pre-built HTML, so you don't have to rely on the demo at all: [dist-updated.zip](https://github.com/lukeed/bee3d/files/1755522/dist-updated.zip)
