### ISSUE TITLE
How do I know the slide that I haveto load via Ajax?

### ISSUE THREAD

**Issue by OscarWilde** [lukeed/bee3d#63]
I've got many slides to load and I need to know at what slide I am to load the correct one. How do I do that?

**Comment by lukeed** [comment]
Hey,

The AJAX solution is not the most elegant thing in the world... I need to update it 🙈 

For now, you can update your `options` on every slide change:

```js
var slider = new Bee3D(elem, options);

slider.el.on('activate', function(event) {
  console.log('This is the activated index: ', event.index);
  // do something based on the new index?
  slider.options.ajax.path = `/api/posts?offset=${event.index}`;
  // ^ update the AJAX path (bad example)
});
```
