### ISSUE TITLE
Stop autoplay after click event on slide

### ISSUE THREAD

**Issue by ldecoker** [lukeed/bee3d#65]
Hello!

Is it possible to stop the autoplay after a click event on one of the slides but without re-initialisation of the slider? When I clicked on the slide, it will flip.

Thx!

**Comment by lukeed** [comment]
Hey~! Yes. You can actually take advantage of the custom events that are _inside_ the Autoplay module.

If you open up the source, you'll see this code:

```js
// start on 'resumeAutoplay' event
self.el.on('resumeAutoplay', start);

// pause on 'pauseAutoplay' event
self.el.on('pauseAutoplay', stop);
```

While this is added for the `pauseHover` option, you can `fire()` the events manually to stop & play the autoplay as desired.

So, somewhere inside your click handler, you can do this:

```js
slider.el.fire('pauseAutoplay');

// somewhere later...

slider.el.fire('resumeAutoplay');
```

Hope that helps! Lemme know
