### ISSUE TITLE
Zoom on slide in Classic mode

### ISSUE THREAD

**Issue by maisondx** [lukeed/bee3d#69]
I am using the classic mode, Is there an option where I can have the background slides smaller and then enlarge when it comes to the center? 

![image](https://user-images.githubusercontent.com/5140453/40523132-131a195a-5f89-11e8-90fc-1db28357f11c.png)

I also would like control the spacing so that they are spaced further apart.
I am not able to build the files, can you send me the non-min versions or JS and CSS.

I recently bought Bee3d. 

Thanks.

**Comment by maisondx** [comment]
nevermind about the non-min versions.

**Comment by lukeed** [comment]
Hey, sorry about the slight delay -- I was traveling. Glad you were able to build it~! 

As for the style questions, those are both CSS related.

* For spacing, see [my answer here](https://github.com/lukeed/bee3d/issues/28#issuecomment-214824021)

* For slide size:

    Within `src/styles/_config.sass`, there are two SASS variables named $slide-w and $slide-h. Changing these will change the size of your slides. All of the slider's effects are calculated from these two values.

    There's also a few issues in this repo already asking the same question. Multiple variations of the same answer for each one 😄 

Closing as it's not an "issue" but please continue to ask questions here if you need more help.

Thanks!

**Comment by maisondx** [comment]
Thank you for you response. I should've checked first if this question was asked before, haha I thought it was unique.

**Comment by lukeed** [comment]
Haha no problem, happy to help
