### ISSUE TITLE
Touches: Only listen to slider's `direction`

### ISSUE THREAD

**Issue by lukeed** [lukeed/bee3d#7]
When swiping on mobile devices, a horizontal slider should ignore any vertical swipes so that scrolling the page can continue without its event-input being hijacked.

**Comment by icdindia** [comment]
yes please, this is very important. In my website the carousel covers the entire first scroll of the page. Now users are not able to scroll down on a mobile.

If I disable touch, the right left swipe doesnt work.
If I enable swipe, nothing happens, the swipe still doesnt work.
If I enable touch, vertical scroll stops working.

Please help at the earliest.

**Comment by eugearias** [comment]
Hi, I have bought this slider and faced the same issue, quite critical for mobile experience. 
Is there any update? Looks like the bug has been open for more than 1 year :(
Thanks

**Comment by lukeed** [comment]
Hi there,

I'm currently on vacation, but when I get back I will look into this. It should be an easy fix!

**Comment by mathishuettl** [comment]
Hello @lukeed 

when do you think this problem is solved?

**Comment by lukeed** [comment]
@mathishuettl This weekend 👍

**Comment by mathishuettl** [comment]
is it fixed?

**Comment by lukeed** [comment]
@mathishuettl Doing it right now actually. :)

**Comment by lukeed** [comment]
Fixed in `2.2.0`. 

Submitting to Envato now. Should be notified of the update within a couple hours! 🎉

**Comment by lukeed** [comment]
@mathishuettl Please let me know if/when Envato emails you with the update. 😃

**Comment by mathishuettl** [comment]
@lukeed hmm i didn't get an information until now..

**Comment by lukeed** [comment]
@mathishuettl Bummer. Sometimes Envato is quick, but I can't ever be certain. 

Glad you got it!

**Comment by mathishuettl** [comment]
@lukeed  hi luke i still got no notification and in envato in the description is this: Last Update 	7 June 16

**Comment by lukeed** [comment]
@mathishuettl  Oh. I thought you got it! Ok, please send me an email at luke.edwards05 at gmail dot com and I will email you the updated ZIP.

The update must still be pending in their system.

**Comment by leotankilevich** [comment]
@lukeed Hi. I got same problem with vertical scroll and envato notification. Envato didnt send me any notifications about update.
