### ISSUE TITLE
Constant speed, not pausing and prevent slider jump

### ISSUE THREAD

**Issue by anthonylan** [lukeed/bee3d#79]
Hi  Lukeed, it's me again.

So for the concave effect is there a way to make the speed constant and prevent it from pausing?

I mean right now it moves and pauses and moves again, thus the circle continues, I added the loop option with continuos enabled, I'd like to know if there is a way to make it move like this: https://shop.theweeknd.com/

Please look at the carousel.

Also when it gets to the end, the slider jumps make to the start. I'm okay it jump, but it is very visible that's what worries me.

Thanks for your support Lukeed.

**Comment by lukeed** [comment]
Hey, I'm not seeing the slider stop or pause at all? I'm wondering if you've updated it since opening this issue.

**Comment by anthonylan** [comment]
let me send you the link to my project

**Comment by anthonylan** [comment]
Hi Lukeed, here is the project:
https://3eebdffe2153.ngrok.io

Noticed its moves, pause, moves, pause and so on

**Comment by anthonylan** [comment]
Also, you can wait to see when the slider gets to the end, see how it jumps back to the beginning

**Comment by lukeed** [comment]
I've watched the carousel on `https://shop.theweeknd.com/` go around 3-6 times – it does not stop or pause.

**Comment by anthonylan** [comment]
Lukeed, I did not say https://shop.theweeknd.com/ pause or stop. I said 'Bee3d concave effect' pause and start as just like many other carousels.

I was asking if it is possible to make it move smoothly like https://shop.theweeknd.com

sorry for the miss understanding

**Comment by anthonylan** [comment]
Look at bee movement: https://lukeed.com/demo/bee3D/#/effects/concave

and look at this: https://shop.theweeknd.com/

spot the difference? I'd like to make Bee3d concave' move smoothly like this => https://shop.theweeknd.com/

**Comment by anthonylan** [comment]
I hope you get me now

**Comment by anthonylan** [comment]
Hi Lukeed, any update yet? I've been waiting for your feedback for about 3 days now

**Comment by lukeed** [comment]
Sorry – I missed the notifications on your follow-ups somehow

You want `loop` and `autoplay` enabled (see Wiki)
Then you'll need to adjust the `autoplay.speed` and/or the CSS transition timings so that the motion seems gradual. Your CSS transition time has to be longer than the `autoplay.speed` value.

This should take you a bulk of the way there:

```js
new Bee3D(element, {
    effect: 'concave',
    autoplay: {
        enabled: true,
        speed: 3000, // 3s per slide, CSS must be slower
    },
    loop: {
        enabled: true,
        continuous: true,
    },
})
```

Also, please remember that I'm only obligated to supply bug/issue support. Anything else is completely voluntarily.

Hope that helps!
